export var Constants = {
    localIPAddress    : '192.168.0.100',
  	myMatApiStartUrl  : 'http://192.168.1.3/start.htm',
    myMatApiIndexUrl  : 'http://192.168.1.3/index.htm',
  	myMatApiUrl       : 'https://www.esferasoluciones.com/api/mymat/',
    storageKeyLang    : 'mymat_lang',
    storageKeyBubble1 : 'MyMat_bubbleRoutineProgram1',
    storageKeyBubble2 : 'MyMat_bubbleRoutineProgram2',
    storageKeyBubble3 : 'MyMat_bubbleRoutineProgram3',
    storageKeyBubble4 : 'MyMat_bubbleRoutineProgram4',
    storageKeyScrollTop : 'MyMat_scrollTop',
    storageKeyCurrentProgram : 'MyMat_currentProgram',
    deviceInfo: 'MyMatDevice',
    test_uuid: 'E5F96E83-146B-4561-850F-343A73BD071A',
    latestRoutinesKey: 'latestRoutines',
    monthNames: [
        "January", "February", "March",
        "April", "May", "June", "July",
        "August", "September", "October",
        "November", "December"
      ],
    shortTitles       : [
                        'earth-element-upper',
                        'fire-element-upper',
                        'metal-element-upper',
                        'water-element-upper',
                        'wood-element-upper',
                        'gallbladder-meridian-upper',
                        'kidney-meridian-upper',
                        'heart-meridian-upper',
                        'large-intestine-meridian-upper',
                        'liver-meridian-upper',
                        'lung-meridian-upper',
                        'pericardium-meridian-upper',
                        'small-intestine-meridian-upper',
                        'spleen-pancreas-meridian-upper',
                        'stomach-meridian-upper',
                        'triple-warmer-meridian-upper',
                        'urinary-bladder-meridian-upper'
                      ]
};
